### ISSUE TITLE
Error when IP times out

### ISSUE THREAD

**Issue by lordeamon** [PaloAltoNetworks/pyjarm#11]
## Describe the bug

When scanning ips and URLs, that does not respond before timeout, pyjarm throw an Error log/message. in some cases in stops the remaining scans, but not everytime.

## Expected behavior

No error log, but maybe a status: no connection(not responding  and a result of JARM: 00000000000000000000000000000000000000000000000000000000000000

## Current behavior

Makes the runtime increase alot, while hanging all scans it seems.

Throws and full error log, with a traceback to asyncio.

 and gives a result of : JARM: |||,|||,|||,|||,|||,|||,|||,|||,|||,|||.
 
 i see that this is the JARM ERROR for Total failure, but compared to the salesforce codebase this scenario seems to eat up alot more time somehow..

## Possible solution

Any fix, or work around will be appreciated

## Steps to reproduce

open console/powershell

run:
pyjarm "IP-address that does not respond"

output > see further down.

## Screenshots

See console output...

## Context

When running a scan either single or from list/file, it throws a Error everytime an ip does not respond, the console out further down is from scanning a single ip.. This behaviour is quite different from the salesforce code base... 

Besides the Error message, its takes up alot of time, even with low timeouts..

this becomes a issues/worry, when doing last batch scans.. Especially since its not clear if its a impactfull error or can be ignored.. 

Any way to help clear my misunderstading, misuse or issue..?

Environment

- Version used:
- newest version and, python 3.9.x
- Win10 and Windows Server 2016

<<SINGLE IP SCAN>>
Console Output:
pyjarm 212.10.184.148
Target: 212.10.184.148:443
ERROR:root:Unknown Exception scanning ScanTarget(host='212.10.184.148', port=443)
Traceback (most recent call last):
  File "c:\program files\python\lib\site-packages\jarm\connection\connection.py", line 47, in jarm_data
    reader, writer = await Connection.prep_connection(conn_target)
  File "c:\program files\python\lib\site-packages\jarm\connection\connection.py", line 25, in prep_connection
    reader, writer = await asyncio.open_connection(
  File "c:\program files\python\lib\asyncio\streams.py", line 52, in open_connection
    transport, _ = await loop.create_connection(
  File "c:\program files\python\lib\asyncio\base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "c:\program files\python\lib\asyncio\base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "c:\program files\python\lib\asyncio\proactor_events.py", line 702, in sock_connect
    return await self._proactor.connect(sock, address)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files\python\lib\asyncio\tasks.py", line 489, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\program files\python\lib\site-packages\jarm\scanner\scanner.py", line 97, in scan_async
    result_list = await Scanner.gather_with_concurrency(concurrency, *tasks)
  File "c:\program files\python\lib\site-packages\jarm\scanner\scanner.py", line 25, in gather_with_concurrency
    return await asyncio.gather(*(sem_task(task) for task in tasks))
  File "c:\program files\python\lib\site-packages\jarm\scanner\scanner.py", line 23, in sem_task
    return await task
  File "c:\program files\python\lib\site-packages\jarm\connection\connection.py", line 124, in jarm_connect
    output = await asyncio.wait_for(fut, timeout=timeout)
  File "c:\program files\python\lib\asyncio\tasks.py", line 491, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
c:\program files\python\lib\asyncio\runners.py:47: RuntimeWarning: coroutine 'Connection.jarm_connect' was never awaited
  _cancel_all_tasks(loop)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
JARM: |||,|||,|||,|||,|||,|||,|||,|||,|||,|||

<<WEBSITE SCAN>>
pyjarm www.virkerdenhervirkelig.dk
Target: www.virkerdenhervirkelig.dk:443
ERROR:root:Unknown Exception scanning ScanTarget(host='www.virkerdenhervirkelig.dk', port=443)
Traceback (most recent call last):
  File "c:\program files\python\lib\site-packages\jarm\validate\validate.py", line 9, in validate_target
    info = socket.getaddrinfo(
  File "c:\program files\python\lib\socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files\python\lib\site-packages\jarm\scanner\scanner.py", line 97, in scan_async
    result_list = await Scanner.gather_with_concurrency(concurrency, *tasks)
  File "c:\program files\python\lib\site-packages\jarm\scanner\scanner.py", line 25, in gather_with_concurrency
    return await asyncio.gather(*(sem_task(task) for task in tasks))
  File "c:\program files\python\lib\site-packages\jarm\scanner\scanner.py", line 23, in sem_task
    return await task
  File "c:\program files\python\lib\site-packages\jarm\connection\connection.py", line 117, in jarm_connect
    target_family, _, _, _, target_addr = Validate.validate_target(
  File "c:\program files\python\lib\site-packages\jarm\validate\validate.py", line 13, in validate_target
    raise PyJARMInvalidTarget("Invalid Target Host")
jarm.exceptions.exceptions.PyJARMInvalidTarget: Invalid Target Host
JARM: |||,|||,|||,|||,|||,|||,|||,|||,|||,|||

**Comment by andrew-paloalto** [comment]
Hi @lordeamon,

Thanks for filing this issue. We'll look into it and see if we can modify the behavior we have here to be closer to the behavior of the original implementation.

**Comment by lordeamon** [comment]
> Hi @lordeamon,
> 
> Thanks for filing this issue. We'll look into it and see if we can modify the behavior we have here to be closer to the behavior of the original implementation.
